# Generated by Django 3.2.6 on 2021-09-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Категории продуктов'},
        ),
    ]
